### ISSUE TITLE
Styling suggestions

### ISSUE THREAD

**Issue by enderwillsaveu** [jeffDevelops/Binaural#2]
Possibly redefinding the size of the game to be sure it will fit within the browser window. I was having to scroll down in order to view the entire game.

 I see that you've already introduced some media queries.

on your about page.
when the query kicks in your title is removed (this only happens in safari i found). 

I think just spending some time playing with your queries would be as much as much direction as I would give because its honestly really solid - just needs some sizing tweaks to make sure everything plays together.

**Comment by jeffDevelops** [comment]
As far as the Safari-only bug goes, the only explanation I have is the text-gradient isn't supported, but I wasn't able to find a solution to the fact that, if you click where the <h1> should be, the text appears, gradient and all! Thanks for bringing this to my attention.
