### ISSUE TITLE
from Hung with love

### ISSUE THREAD

**Issue by hungmuha** [jeffDevelops/Binaural#3]
sweet jesus, over 1800 line of css code. The game look greats

On screen responsive, on certain size the element seems to stack over each other. Maybe just get your css straight out on those

there are no reset button to play again.

**Comment by jeffDevelops** [comment]
I was able to got the game working somewhat cohesively on mobile, but Bootstrap classes are blocking me for tablet sizes. I'm going to close this issue, but I'm still working on tablet sizes.
